title: Olive di Pietro
baseurl: /
permalink: '/:title/'
plugins:
  - jekyll-menus
  - jekyll-sitemap
url: "https://olivedipietro.com"
collections:
  posts:
    permalink: '/posts/:title/'
sass:
  style: nested
  precision: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  
